<?php

namespace Database\Seeders;

use App\Models\Afiliado;
use App\Models\User;
use Illuminate\Database\Seeder;

class AfiliadoMenorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->command->info('Creando afiliados menores de edad (17 años o menos)...');

        $adminUser = User::where('email', 'admin@example.com')->first();

        $afiliadosMenores = [
            [
                'primer_nombre' => 'Santiago',
                'segundo_nombre' => 'Andrés',
                'primer_apellido' => 'Rodríguez',
                'segundo_apellido' => 'García',
                'fecha_nacimiento' => now()->subYears(17)->subMonths(3),
                'genero' => 'masculino',
                'estado_civil' => 'soltero',
                'nacionalidad' => 'Colombiana',
                'tipo_documento' => 'tarjeta_identidad',
                'numero_documento' => 'TI1234567890',
                'telefono' => null,
                'celular' => '3001111111',
                'email' => 'santiago.rodriguez@example.com',
                'direccion_residencia' => 'Calle 100 #50-30',
                'barrio' => 'Usaquén',
                'ciudad' => 'Bogotá',
                'departamento' => 'Cundinamarca',
                'pais' => 'Colombia',
                'codigo_postal' => '110111',
                'nombre_conyuge' => null,
                'numero_hijos' => 0,
                'personas_a_cargo' => 0,
                'informacion_familiar' => 'Vive con padres y dos hermanos menores. Padre: Juan Rodríguez, Madre: María García.',
                'ocupacion' => 'Estudiante',
                'lugar_trabajo' => null,
                'cargo' => null,
                'ingresos_mensuales' => null,
                'tipo_empleo' => 'estudiante',
                'descripcion_laboral' => null,
                'nivel_educativo' => 'secundaria',
                'institucion_educativa' => 'Colegio Distrital San José',
                'titulo_obtenido' => null,
                'estudiando_actualmente' => true,
                'tiene_seguro_salud' => true,
                'tipo_seguro_salud' => 'EPS',
                'eps' => 'Sura',
                'condiciones_medicas' => null,
                'medicamentos_permanentes' => null,
                'alergias' => 'Polvo',
                'observaciones' => 'Estudiante de grado 11. Participa en actividades deportivas.',
                'estado' => 'activo',
                'fecha_registro' => now()->subMonths(2),
                'user_id' => $adminUser?->id,
            ],
            [
                'primer_nombre' => 'Valentina',
                'segundo_nombre' => 'Sofía',
                'primer_apellido' => 'Martínez',
                'segundo_apellido' => 'López',
                'fecha_nacimiento' => now()->subYears(15)->subMonths(6),
                'genero' => 'femenino',
                'estado_civil' => 'soltero',
                'nacionalidad' => 'Colombiana',
                'tipo_documento' => 'tarjeta_identidad',
                'numero_documento' => 'TI9876543210',
                'telefono' => '6012345678',
                'celular' => '3002222222',
                'email' => 'valentina.martinez@example.com',
                'direccion_residencia' => 'Carrera 15 #45-67',
                'barrio' => 'La Candelaria',
                'ciudad' => 'Bogotá',
                'departamento' => 'Cundinamarca',
                'pais' => 'Colombia',
                'codigo_postal' => '110111',
                'nombre_conyuge' => null,
                'numero_hijos' => 0,
                'personas_a_cargo' => 0,
                'informacion_familiar' => 'Vive con madre soltera. Madre: Carmen López. Tiene un hermano mayor.',
                'ocupacion' => 'Estudiante',
                'lugar_trabajo' => null,
                'cargo' => null,
                'ingresos_mensuales' => null,
                'tipo_empleo' => 'estudiante',
                'descripcion_laboral' => null,
                'nivel_educativo' => 'secundaria',
                'institucion_educativa' => 'Instituto Técnico Industrial',
                'titulo_obtenido' => null,
                'estudiando_actualmente' => true,
                'tiene_seguro_salud' => true,
                'tipo_seguro_salud' => 'Subsidiado',
                'eps' => 'Sisbén',
                'condiciones_medicas' => null,
                'medicamentos_permanentes' => null,
                'alergias' => null,
                'observaciones' => 'Estudiante de grado 9. Interesada en artes y música.',
                'estado' => 'activo',
                'fecha_registro' => now()->subMonths(4),
                'user_id' => $adminUser?->id,
            ],
            [
                'primer_nombre' => 'Mateo',
                'segundo_nombre' => null,
                'primer_apellido' => 'González',
                'segundo_apellido' => 'Pérez',
                'fecha_nacimiento' => now()->subYears(12)->subMonths(8),
                'genero' => 'masculino',
                'estado_civil' => 'soltero',
                'nacionalidad' => 'Colombiana',
                'tipo_documento' => 'tarjeta_identidad',
                'numero_documento' => 'TI1122334455',
                'telefono' => '6023456789',
                'celular' => null,
                'email' => null,
                'direccion_residencia' => 'Avenida 68 #25-40',
                'barrio' => 'Chapinero',
                'ciudad' => 'Bogotá',
                'departamento' => 'Cundinamarca',
                'pais' => 'Colombia',
                'codigo_postal' => '110221',
                'nombre_conyuge' => null,
                'numero_hijos' => 0,
                'personas_a_cargo' => 0,
                'informacion_familiar' => 'Vive con ambos padres y una hermana menor. Familia nuclear.',
                'ocupacion' => 'Estudiante',
                'lugar_trabajo' => null,
                'cargo' => null,
                'ingresos_mensuales' => null,
                'tipo_empleo' => 'estudiante',
                'descripcion_laboral' => null,
                'nivel_educativo' => 'primaria',
                'institucion_educativa' => 'Colegio Bilingüe San Patricio',
                'titulo_obtenido' => null,
                'estudiando_actualmente' => true,
                'tiene_seguro_salud' => true,
                'tipo_seguro_salud' => 'EPS',
                'eps' => 'Nueva EPS',
                'condiciones_medicas' => 'Asma leve',
                'medicamentos_permanentes' => 'Inhalador salbutamol (uso ocasional)',
                'alergias' => 'Ácaros del polvo',
                'observaciones' => 'Estudiante de grado 6. Requiere seguimiento médico por asma.',
                'estado' => 'activo',
                'fecha_registro' => now()->subMonths(6),
                'user_id' => $adminUser?->id,
            ],
            [
                'primer_nombre' => 'Isabella',
                'segundo_nombre' => 'María',
                'primer_apellido' => 'Sánchez',
                'segundo_apellido' => 'Torres',
                'fecha_nacimiento' => now()->subYears(10)->subMonths(2),
                'genero' => 'femenino',
                'estado_civil' => 'soltero',
                'nacionalidad' => 'Colombiana',
                'tipo_documento' => 'tarjeta_identidad',
                'numero_documento' => 'TI5566778899',
                'telefono' => '6034567890',
                'celular' => null,
                'email' => null,
                'direccion_residencia' => 'Calle 72 #10-20',
                'barrio' => 'Teusaquillo',
                'ciudad' => 'Bogotá',
                'departamento' => 'Cundinamarca',
                'pais' => 'Colombia',
                'codigo_postal' => '110311',
                'nombre_conyuge' => null,
                'numero_hijos' => 0,
                'personas_a_cargo' => 0,
                'informacion_familiar' => 'Vive con madre y abuela. Padre ausente. Tiene dos hermanos mayores.',
                'ocupacion' => 'Estudiante',
                'lugar_trabajo' => null,
                'cargo' => null,
                'ingresos_mensuales' => null,
                'tipo_empleo' => 'estudiante',
                'descripcion_laboral' => null,
                'nivel_educativo' => 'primaria',
                'institucion_educativa' => 'Escuela Primaria Los Rosales',
                'titulo_obtenido' => null,
                'estudiando_actualmente' => true,
                'tiene_seguro_salud' => true,
                'tipo_seguro_salud' => 'Subsidiado',
                'eps' => 'Sisbén',
                'condiciones_medicas' => null,
                'medicamentos_permanentes' => null,
                'alergias' => null,
                'observaciones' => 'Estudiante de grado 4. Participa en programa de refuerzo escolar.',
                'estado' => 'activo',
                'fecha_registro' => now()->subMonths(8),
                'user_id' => $adminUser?->id,
            ],
            [
                'primer_nombre' => 'Sebastián',
                'segundo_nombre' => 'David',
                'primer_apellido' => 'Ramírez',
                'segundo_apellido' => 'Vargas',
                'fecha_nacimiento' => now()->subYears(16)->subMonths(4),
                'genero' => 'masculino',
                'estado_civil' => 'soltero',
                'nacionalidad' => 'Colombiana',
                'tipo_documento' => 'tarjeta_identidad',
                'numero_documento' => 'TI9988776655',
                'telefono' => null,
                'celular' => '3003333333',
                'email' => 'sebastian.ramirez@example.com',
                'direccion_residencia' => 'Carrera 30 #50-15',
                'barrio' => 'Kennedy',
                'ciudad' => 'Bogotá',
                'departamento' => 'Cundinamarca',
                'pais' => 'Colombia',
                'codigo_postal' => '111111',
                'nombre_conyuge' => null,
                'numero_hijos' => 0,
                'personas_a_cargo' => 0,
                'informacion_familiar' => 'Vive con padre y madrastra. Tiene dos medio hermanos.',
                'ocupacion' => 'Estudiante',
                'lugar_trabajo' => null,
                'cargo' => null,
                'ingresos_mensuales' => null,
                'tipo_empleo' => 'estudiante',
                'descripcion_laboral' => null,
                'nivel_educativo' => 'secundaria',
                'institucion_educativa' => 'Colegio Técnico Distrital',
                'titulo_obtenido' => null,
                'estudiando_actualmente' => true,
                'tiene_seguro_salud' => true,
                'tipo_seguro_salud' => 'EPS',
                'eps' => 'Sanitas',
                'condiciones_medicas' => null,
                'medicamentos_permanentes' => null,
                'alergias' => 'Picaduras de insectos',
                'observaciones' => 'Estudiante de grado 10. Interesado en tecnología y programación.',
                'estado' => 'activo',
                'fecha_registro' => now()->subMonths(3),
                'user_id' => $adminUser?->id,
            ],
            [
                'primer_nombre' => 'Mariana',
                'segundo_nombre' => 'Alejandra',
                'primer_apellido' => 'Castro',
                'segundo_apellido' => 'Mendoza',
                'fecha_nacimiento' => now()->subYears(8)->subMonths(10),
                'genero' => 'femenino',
                'estado_civil' => 'soltero',
                'nacionalidad' => 'Colombiana',
                'tipo_documento' => 'tarjeta_identidad',
                'numero_documento' => 'TI4433221100',
                'telefono' => '6045678901',
                'celular' => null,
                'email' => null,
                'direccion_residencia' => 'Calle 13 #45-67',
                'barrio' => 'Centro',
                'ciudad' => 'Bogotá',
                'departamento' => 'Cundinamarca',
                'pais' => 'Colombia',
                'codigo_postal' => '110111',
                'nombre_conyuge' => null,
                'numero_hijos' => 0,
                'personas_a_cargo' => 0,
                'informacion_familiar' => 'Vive con ambos padres. Familia estable. Tiene un hermano menor.',
                'ocupacion' => 'Estudiante',
                'lugar_trabajo' => null,
                'cargo' => null,
                'ingresos_mensuales' => null,
                'tipo_empleo' => 'estudiante',
                'descripcion_laboral' => null,
                'nivel_educativo' => 'primaria',
                'institucion_educativa' => 'Colegio Primario San Francisco',
                'titulo_obtenido' => null,
                'estudiando_actualmente' => true,
                'tiene_seguro_salud' => true,
                'tipo_seguro_salud' => 'EPS',
                'eps' => 'Comfenalco',
                'condiciones_medicas' => null,
                'medicamentos_permanentes' => null,
                'alergias' => null,
                'observaciones' => 'Estudiante de grado 2. Participa en actividades recreativas.',
                'estado' => 'activo',
                'fecha_registro' => now()->subMonths(10),
                'user_id' => $adminUser?->id,
            ],
            [
                'primer_nombre' => 'Nicolás',
                'segundo_nombre' => 'Felipe',
                'primer_apellido' => 'Herrera',
                'segundo_apellido' => 'Jiménez',
                'fecha_nacimiento' => now()->subYears(14)->subMonths(1),
                'genero' => 'masculino',
                'estado_civil' => 'soltero',
                'nacionalidad' => 'Colombiana',
                'tipo_documento' => 'tarjeta_identidad',
                'numero_documento' => 'TI7788990011',
                'telefono' => null,
                'celular' => '3004444444',
                'email' => 'nicolas.herrera@example.com',
                'direccion_residencia' => 'Avenida Ciudad de Cali #80-50',
                'barrio' => 'Suba',
                'ciudad' => 'Bogotá',
                'departamento' => 'Cundinamarca',
                'pais' => 'Colombia',
                'codigo_postal' => '111321',
                'nombre_conyuge' => null,
                'numero_hijos' => 0,
                'personas_a_cargo' => 0,
                'informacion_familiar' => 'Vive con madre soltera. Madre: Patricia Jiménez. Tiene una hermana mayor.',
                'ocupacion' => 'Estudiante',
                'lugar_trabajo' => null,
                'cargo' => null,
                'ingresos_mensuales' => null,
                'tipo_empleo' => 'estudiante',
                'descripcion_laboral' => null,
                'nivel_educativo' => 'secundaria',
                'institucion_educativa' => 'Colegio Distrital La Esperanza',
                'titulo_obtenido' => null,
                'estudiando_actualmente' => true,
                'tiene_seguro_salud' => true,
                'tipo_seguro_salud' => 'Subsidiado',
                'eps' => 'Sisbén',
                'condiciones_medicas' => null,
                'medicamentos_permanentes' => null,
                'alergias' => 'Lácteos',
                'observaciones' => 'Estudiante de grado 8. Requiere dieta especial por alergia a lácteos.',
                'estado' => 'activo',
                'fecha_registro' => now()->subMonths(5),
                'user_id' => $adminUser?->id,
            ],
            [
                'primer_nombre' => 'Sofía',
                'segundo_nombre' => null,
                'primer_apellido' => 'Moreno',
                'segundo_apellido' => 'Díaz',
                'fecha_nacimiento' => now()->subYears(6)->subMonths(5),
                'genero' => 'femenino',
                'estado_civil' => 'soltero',
                'nacionalidad' => 'Colombiana',
                'tipo_documento' => 'tarjeta_identidad',
                'numero_documento' => 'TI2233445566',
                'telefono' => '6056789012',
                'celular' => null,
                'email' => null,
                'direccion_residencia' => 'Carrera 7 #32-10',
                'barrio' => 'La Macarena',
                'ciudad' => 'Bogotá',
                'departamento' => 'Cundinamarca',
                'pais' => 'Colombia',
                'codigo_postal' => '110311',
                'nombre_conyuge' => null,
                'numero_hijos' => 0,
                'personas_a_cargo' => 0,
                'informacion_familiar' => 'Vive con ambos padres. Familia nuclear estable.',
                'ocupacion' => 'Estudiante',
                'lugar_trabajo' => null,
                'cargo' => null,
                'ingresos_mensuales' => null,
                'tipo_empleo' => 'estudiante',
                'descripcion_laboral' => null,
                'nivel_educativo' => 'primaria',
                'institucion_educativa' => 'Jardín Infantil y Colegio San Ángel',
                'titulo_obtenido' => null,
                'estudiando_actualmente' => true,
                'tiene_seguro_salud' => true,
                'tipo_seguro_salud' => 'EPS',
                'eps' => 'Sura',
                'condiciones_medicas' => null,
                'medicamentos_permanentes' => null,
                'alergias' => null,
                'observaciones' => 'Estudiante de transición. Participa en actividades lúdicas y recreativas.',
                'estado' => 'activo',
                'fecha_registro' => now()->subMonths(12),
                'user_id' => $adminUser?->id,
            ],
            [
                'primer_nombre' => 'Daniel',
                'segundo_nombre' => 'Esteban',
                'primer_apellido' => 'Ospina',
                'segundo_apellido' => 'Ruiz',
                'fecha_nacimiento' => now()->subYears(13)->subMonths(7),
                'genero' => 'masculino',
                'estado_civil' => 'soltero',
                'nacionalidad' => 'Colombiana',
                'tipo_documento' => 'tarjeta_identidad',
                'numero_documento' => 'TI3344556677',
                'telefono' => null,
                'celular' => '3005555555',
                'email' => 'daniel.ospina@example.com',
                'direccion_residencia' => 'Calle 63 #10-30',
                'barrio' => 'Quinta Camacho',
                'ciudad' => 'Bogotá',
                'departamento' => 'Cundinamarca',
                'pais' => 'Colombia',
                'codigo_postal' => '110221',
                'nombre_conyuge' => null,
                'numero_hijos' => 0,
                'personas_a_cargo' => 0,
                'informacion_familiar' => 'Vive con padre y madre. Tiene un hermano gemelo.',
                'ocupacion' => 'Estudiante',
                'lugar_trabajo' => null,
                'cargo' => null,
                'ingresos_mensuales' => null,
                'tipo_empleo' => 'estudiante',
                'descripcion_laboral' => null,
                'nivel_educativo' => 'secundaria',
                'institucion_educativa' => 'Colegio Bilingüe Los Andes',
                'titulo_obtenido' => null,
                'estudiando_actualmente' => true,
                'tiene_seguro_salud' => true,
                'tipo_seguro_salud' => 'EPS',
                'eps' => 'Nueva EPS',
                'condiciones_medicas' => null,
                'medicamentos_permanentes' => null,
                'alergias' => null,
                'observaciones' => 'Estudiante de grado 7. Participa en equipo de fútbol del colegio.',
                'estado' => 'activo',
                'fecha_registro' => now()->subMonths(7),
                'user_id' => $adminUser?->id,
            ],
            [
                'primer_nombre' => 'Camila',
                'segundo_nombre' => 'Andrea',
                'primer_apellido' => 'Vega',
                'segundo_apellido' => 'Morales',
                'fecha_nacimiento' => now()->subYears(11)->subMonths(9),
                'genero' => 'femenino',
                'estado_civil' => 'soltero',
                'nacionalidad' => 'Colombiana',
                'tipo_documento' => 'tarjeta_identidad',
                'numero_documento' => 'TI4455667788',
                'telefono' => '6067890123',
                'celular' => null,
                'email' => null,
                'direccion_residencia' => 'Carrera 50 #100-20',
                'barrio' => 'Engativá',
                'ciudad' => 'Bogotá',
                'departamento' => 'Cundinamarca',
                'pais' => 'Colombia',
                'codigo_postal' => '111211',
                'nombre_conyuge' => null,
                'numero_hijos' => 0,
                'personas_a_cargo' => 0,
                'informacion_familiar' => 'Vive con abuela y tía. Madre trabaja fuera de la ciudad. Tiene un hermano menor.',
                'ocupacion' => 'Estudiante',
                'lugar_trabajo' => null,
                'cargo' => null,
                'ingresos_mensuales' => null,
                'tipo_empleo' => 'estudiante',
                'descripcion_laboral' => null,
                'nivel_educativo' => 'primaria',
                'institucion_educativa' => 'Escuela Primaria El Progreso',
                'titulo_obtenido' => null,
                'estudiando_actualmente' => true,
                'tiene_seguro_salud' => true,
                'tipo_seguro_salud' => 'Subsidiado',
                'eps' => 'Sisbén',
                'condiciones_medicas' => null,
                'medicamentos_permanentes' => null,
                'alergias' => null,
                'observaciones' => 'Estudiante de grado 5. Requiere apoyo académico adicional.',
                'estado' => 'activo',
                'fecha_registro' => now()->subMonths(9),
                'user_id' => $adminUser?->id,
            ],
        ];

        foreach ($afiliadosMenores as $afiliadoData) {
            $afiliado = Afiliado::create($afiliadoData);
            $edad = $afiliado->edad;
            $this->command->info("  ✓ Afiliado menor creado: {$afiliado->nombre_completo} ({$edad} años)");
        }

        $this->command->info('¡Seeder de afiliados menores completado exitosamente!');
    }
}

