<?php

namespace Database\Seeders;

use App\Models\Afiliado;
use App\Models\User;
use Illuminate\Database\Seeder;

class AfiliadoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->command->info('Creando afiliados de ejemplo...');

        $adminUser = User::where('email', 'admin@example.com')->first();

        $afiliados = [
            [
                'primer_nombre' => 'Juan',
                'segundo_nombre' => 'Carlos',
                'primer_apellido' => 'García',
                'segundo_apellido' => 'López',
                'fecha_nacimiento' => '1985-05-15',
                'genero' => 'masculino',
                'estado_civil' => 'casado',
                'nacionalidad' => 'Colombiana',
                'tipo_documento' => 'cedula',
                'numero_documento' => '1234567890',
                'telefono' => '6012345678',
                'celular' => '3001234567',
                'email' => 'juan.garcia@example.com',
                'direccion_residencia' => 'Calle 123 #45-67',
                'barrio' => 'Centro',
                'ciudad' => 'Bogotá',
                'departamento' => 'Cundinamarca',
                'pais' => 'Colombia',
                'codigo_postal' => '110111',
                'nombre_conyuge' => 'María García',
                'numero_hijos' => 2,
                'personas_a_cargo' => 3,
                'informacion_familiar' => 'Vive con esposa y dos hijos menores de edad.',
                'ocupacion' => 'Ingeniero de Sistemas',
                'lugar_trabajo' => 'Empresa Tecnológica S.A.',
                'cargo' => 'Desarrollador Senior',
                'ingresos_mensuales' => 3500000.00,
                'tipo_empleo' => 'empleado',
                'descripcion_laboral' => 'Desarrollo de software y gestión de proyectos tecnológicos.',
                'nivel_educativo' => 'universitario',
                'institucion_educativa' => 'Universidad Nacional',
                'titulo_obtenido' => 'Ingeniero de Sistemas',
                'estudiando_actualmente' => false,
                'tiene_seguro_salud' => true,
                'tipo_seguro_salud' => 'EPS',
                'eps' => 'Sura',
                'condiciones_medicas' => 'Ninguna condición médica relevante.',
                'medicamentos_permanentes' => 'Ninguno',
                'alergias' => 'Polen',
                'observaciones' => 'Afiliado activo desde hace 3 años.',
                'estado' => 'activo',
                'fecha_registro' => now()->subYears(3),
                'user_id' => $adminUser?->id,
            ],
            [
                'primer_nombre' => 'María',
                'segundo_nombre' => 'Fernanda',
                'primer_apellido' => 'Rodríguez',
                'segundo_apellido' => 'Martínez',
                'fecha_nacimiento' => '1990-08-22',
                'genero' => 'femenino',
                'estado_civil' => 'soltero',
                'nacionalidad' => 'Colombiana',
                'tipo_documento' => 'cedula',
                'numero_documento' => '9876543210',
                'telefono' => '6023456789',
                'celular' => '3009876543',
                'email' => 'maria.rodriguez@example.com',
                'direccion_residencia' => 'Avenida 456 #78-90',
                'barrio' => 'Poblado',
                'ciudad' => 'Medellín',
                'departamento' => 'Antioquia',
                'pais' => 'Colombia',
                'codigo_postal' => '050021',
                'nombre_conyuge' => null,
                'numero_hijos' => 0,
                'personas_a_cargo' => 0,
                'informacion_familiar' => 'Vive sola.',
                'ocupacion' => 'Diseñadora Gráfica',
                'lugar_trabajo' => 'Estudio Creativo',
                'cargo' => 'Diseñadora Senior',
                'ingresos_mensuales' => 2800000.00,
                'tipo_empleo' => 'independiente',
                'descripcion_laboral' => 'Diseño gráfico y branding para empresas.',
                'nivel_educativo' => 'universitario',
                'institucion_educativa' => 'Universidad de Antioquia',
                'titulo_obtenido' => 'Diseñadora Gráfica',
                'estudiando_actualmente' => true,
                'tiene_seguro_salud' => true,
                'tipo_seguro_salud' => 'EPS',
                'eps' => 'Nueva EPS',
                'condiciones_medicas' => null,
                'medicamentos_permanentes' => null,
                'alergias' => null,
                'observaciones' => 'Estudiante de maestría en diseño.',
                'estado' => 'activo',
                'fecha_registro' => now()->subMonths(6),
                'user_id' => $adminUser?->id,
            ],
            [
                'primer_nombre' => 'Carlos',
                'segundo_nombre' => 'Alberto',
                'primer_apellido' => 'Pérez',
                'segundo_apellido' => 'González',
                'fecha_nacimiento' => '1978-12-10',
                'genero' => 'masculino',
                'estado_civil' => 'casado',
                'nacionalidad' => 'Colombiana',
                'tipo_documento' => 'cedula',
                'numero_documento' => '1122334455',
                'telefono' => '6034567890',
                'celular' => '3012345678',
                'email' => 'carlos.perez@example.com',
                'direccion_residencia' => 'Carrera 789 #12-34',
                'barrio' => 'La Candelaria',
                'ciudad' => 'Cali',
                'departamento' => 'Valle del Cauca',
                'pais' => 'Colombia',
                'codigo_postal' => '760001',
                'nombre_conyuge' => 'Ana Pérez',
                'numero_hijos' => 3,
                'personas_a_cargo' => 4,
                'informacion_familiar' => 'Vive con esposa y tres hijos. Uno de ellos con discapacidad.',
                'ocupacion' => 'Comerciante',
                'lugar_trabajo' => 'Mercado Central',
                'cargo' => 'Propietario',
                'ingresos_mensuales' => 2500000.00,
                'tipo_empleo' => 'independiente',
                'descripcion_laboral' => 'Venta de productos alimenticios.',
                'nivel_educativo' => 'secundaria',
                'institucion_educativa' => 'Colegio Nacional',
                'titulo_obtenido' => 'Bachiller',
                'estudiando_actualmente' => false,
                'tiene_seguro_salud' => true,
                'tipo_seguro_salud' => 'Subsidiado',
                'eps' => 'Sisbén',
                'condiciones_medicas' => 'Hipertensión',
                'medicamentos_permanentes' => 'Losartan 50mg diario',
                'alergias' => null,
                'observaciones' => 'Requiere seguimiento médico por hipertensión.',
                'estado' => 'activo',
                'fecha_registro' => now()->subYears(2),
                'user_id' => $adminUser?->id,
            ],
            [
                'primer_nombre' => 'Laura',
                'segundo_nombre' => 'Isabel',
                'primer_apellido' => 'Sánchez',
                'segundo_apellido' => 'Torres',
                'fecha_nacimiento' => '1995-03-18',
                'genero' => 'femenino',
                'estado_civil' => 'union_libre',
                'nacionalidad' => 'Colombiana',
                'tipo_documento' => 'cedula',
                'numero_documento' => '5566778899',
                'telefono' => '6045678901',
                'celular' => '3023456789',
                'email' => 'laura.sanchez@example.com',
                'direccion_residencia' => 'Calle 90 #11-23',
                'barrio' => 'Chapinero',
                'ciudad' => 'Bogotá',
                'departamento' => 'Cundinamarca',
                'pais' => 'Colombia',
                'codigo_postal' => '110221',
                'nombre_conyuge' => 'Pedro Sánchez',
                'numero_hijos' => 1,
                'personas_a_cargo' => 2,
                'informacion_familiar' => 'Vive en unión libre con su pareja y un hijo.',
                'ocupacion' => 'Enfermera',
                'lugar_trabajo' => 'Hospital Central',
                'cargo' => 'Enfermera Jefe',
                'ingresos_mensuales' => 3200000.00,
                'tipo_empleo' => 'empleado',
                'descripcion_laboral' => 'Atención de pacientes y gestión de turnos.',
                'nivel_educativo' => 'tecnico',
                'institucion_educativa' => 'SENA',
                'titulo_obtenido' => 'Técnico en Enfermería',
                'estudiando_actualmente' => true,
                'tiene_seguro_salud' => true,
                'tipo_seguro_salud' => 'EPS',
                'eps' => 'Sanitas',
                'condiciones_medicas' => null,
                'medicamentos_permanentes' => null,
                'alergias' => 'Penicilina',
                'observaciones' => 'Estudiando para obtener título profesional.',
                'estado' => 'activo',
                'fecha_registro' => now()->subMonths(8),
                'user_id' => $adminUser?->id,
            ],
            [
                'primer_nombre' => 'Roberto',
                'segundo_nombre' => null,
                'primer_apellido' => 'Mendoza',
                'segundo_apellido' => 'Vargas',
                'fecha_nacimiento' => '1965-07-25',
                'genero' => 'masculino',
                'estado_civil' => 'divorciado',
                'nacionalidad' => 'Colombiana',
                'tipo_documento' => 'cedula',
                'numero_documento' => '9988776655',
                'telefono' => '6056789012',
                'celular' => '3034567890',
                'email' => 'roberto.mendoza@example.com',
                'direccion_residencia' => 'Carrera 50 #30-40',
                'barrio' => 'Bello',
                'ciudad' => 'Medellín',
                'departamento' => 'Antioquia',
                'pais' => 'Colombia',
                'codigo_postal' => '051050',
                'nombre_conyuge' => null,
                'numero_hijos' => 2,
                'personas_a_cargo' => 1,
                'informacion_familiar' => 'Divorciado, tiene custodia de un hijo menor.',
                'ocupacion' => 'Jubilado',
                'lugar_trabajo' => null,
                'cargo' => null,
                'ingresos_mensuales' => 1200000.00,
                'tipo_empleo' => 'jubilado',
                'descripcion_laboral' => 'Pensión de jubilación.',
                'nivel_educativo' => 'secundaria',
                'institucion_educativa' => 'Colegio Departamental',
                'titulo_obtenido' => 'Bachiller',
                'estudiando_actualmente' => false,
                'tiene_seguro_salud' => true,
                'tipo_seguro_salud' => 'EPS',
                'eps' => 'Comfenalco',
                'condiciones_medicas' => 'Diabetes tipo 2',
                'medicamentos_permanentes' => 'Metformina 500mg dos veces al día',
                'alergias' => null,
                'observaciones' => 'Requiere seguimiento por diabetes.',
                'estado' => 'activo',
                'fecha_registro' => now()->subMonths(12),
                'user_id' => $adminUser?->id,
            ],
        ];

        foreach ($afiliados as $afiliadoData) {
            $afiliado = Afiliado::create($afiliadoData);
            $this->command->info("  ✓ Afiliado creado: {$afiliado->nombre_completo}");
        }

        $this->command->info('¡Seeder de afiliados completado exitosamente!');
    }
}

